### ISSUE TITLE
An exception occurred - Data abort

### ISSUE THREAD

**Issue by jojobear88** [KunoichiZ/SoVEU-NTR-Plugin#1]
When using NTR Plugin on FE Echoes EU Region Free version, the game crashed.

System model: Old 3DS EU
Firmware: 11.5.0-38E
Boot Method: B9S/ Boot9Strap
Luma3DS version: 8.1

Explanation of the issue:
An exception occurred screen pops up after enable NTR plugins. If plugins not enabled, the game will run without crashed.

Steps to reproduce:
1. Open BootNTR 3.2
2. Open Fire Emblem Echoes SoV EU
3. Press select and enable plugin
4. Play the game
5. Luma will pop up with the exception screen.

An exception occurred
Processor: ARM11 (core 0)
Exception type:  data abort
Current process: 00040000001B4100

**Comment by KunoichiZ** [comment]
I cannot help you with Luma3DS related crashes, nor do I have an EU system/EU copy of the game to test anything.
